describe('template spec', () => {
  it('Success Choose Product Women Tops', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.contains('Sign In').click()
    cy.url().should('include','customer/account/login/referer')
    cy.get('#email').type('fahmidjuwan@mail.com')
    cy.get('[title="Password"]').type('Djuwan@111')
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2 > span').click()
    cy.url().should('include','magento.softwaretestingboard.com')
    cy.get('#ui-id-3 > span').click()
    cy.get('.categories-menu > :nth-child(2) > :nth-child(1) > a').click()
    cy.get(':nth-child(1) > .product-item-info > .photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
    cy.get('#option-label-size-143-item-169').click()
    cy.get('#option-label-color-93-item-53').click()
    cy.get('#product-addtocart-button').click()
  })
})